apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers: 
      - name: node-exporter
        image: prom/node-exporter
        ports:
        - containerPort: 9100
        args:
        - --path.rootfs=/rootfs'
        volumeMounts:
        - name: rootfs
          mountPath: /rootfs
      volumes:
      - name: rootfs
        hostPath:
          path: /
